apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    app: maysql-app
spec:
  containers:
    - name: maysql-container
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password 
        - name: MYSQL_DATABASE
          value: est_kubernetes